language: node_js
dist: xenial
branches:
  except:
  - "/^untagged.*/"
node_js:
- stable
install:
- true
script:
- cd $TRAVIS_BUILD_DIR
- sh ./appimage/do_stuff.sh
- 'true'
- pwd
- ls -l
before_deploy:
- pwd
- cd $TRAVIS_BUILD_DIR
- pwd
- find . -iname 'Rakudo*AppImage'
- find .. -iname 'Rakudo*AppImage'
- cp ./appimage/out/*.AppImage out/
- cp ../appimage/out/*.AppImage out/
- cp ../out/*.AppImage out/
- cp ./out/*.AppImage out/
deploy:
  provider: releases
  api_key:
    secure: gsuyZMKsAUtEUIXJrh9zSdCK/fLCK409vLaLJVgGlYmf2JQm8dqtc89uH68Zjwh4nIoNKM7WCNqPn4C4vfU98IID1IgmqMpTyJzhMyia9AEeZN8VMP5oyFARZ/awqzU5cO4u38qWBnBzzUuxM42hYIgj19/9oj/AxOVHCZKJRYvgkFcb3GCUFrWfjIzWTQb9TkwmD1lj+7q9406mOm1/GUOeE2bm1X6xVpL8L1sWm+4ynhkbZtZ+qrZgutFiRinJxyFYivMwXpbjosGXoCGEfFhevh5gozG1ZP6P7S4ryj7ckBUohdH+tDzNFzj5fmxMeGxfSAxKoZa8V9xTwgf9Fb79K2sx2AwguPynJ+uLofU8JVJiVBO1fiUEZgRlh1byERbsF1PS3OguTYvpjJfyCc+z9IBlrwoU6cRFO0J68TgYq2A4tnqFTXXFtWlBTXK+jTqjsEIVk6D1epXA/WiiPWeSE563NZtX5RphKlriAHrlIpnxvi6bJyboJqlTGQiQdtgzgVhxxkSNeBwSr3ivwS/jPTimTJdnGsNaLdlQ3kWlmcpuGDdAKH/DAl8xWeNClVLWmiWu2am+FjGZe4AzdatUnyS1oSZxHuUn8f65+B99EfG+4Jbiq2raU+TGeOoZfX6HSoVLgtQzCFDAZKgsjRmJju2Npy8uoVkIouXKtZU=
  file: out/*.AppImage
  file_glob: true
  draft: true
  on:
    repo: timo/rakudo-appimage
  skip_cleanup: 'true'
